export default {
  'auth.title': 'قرآن کتاب امید و آرامش',
  'auth.description': 'مسابقه در جستجوی آرامش',
  'auth.welcome': 'خوش آمدید',
  'auth.login': 'ورود',
  'auth.register': 'ثبت نام',
  'auth.forgotPassword': 'فراموشی رمز عبور',
  'auth.resetPassword': 'بازیابی رمز عبور',
  'auth.nationalCode': 'کد ملی',
  'auth.phoneNumber': 'تلفن همراه',
  'auth.confirmPassword': 'تایید رمز عبور',
  'auth.rememberMe': 'مرا به خاطر بسپار',
  'auth.firstName': 'نام',
  'auth.lastName': 'نام خانوادگی',  
  'quiz.title': 'سوال',
  'quiz.submit': 'ثبت',
};
