export default {
  'auth.title': 'قرآن کتاب امید و آرامش',
  'auth.description': 'مسابقه در جستجوی آرامش',
  'auth.welcome': 'خوش آمدید',
  'auth.login': 'ورود',
  'auth.register': 'ثبت نام',
  'auth.forgotPassword': 'فراموشی رمز عبور',
  'auth.resetPassword': 'بازیابی رمز عبور',
  'auth.nationalCode': 'کد ملی',
  'auth.phoneNumber': 'تلفن همراه',
  'auth.confirmPassword': 'تایید رمز عبور',
  'auth.rememberMe': 'مرا به خاطر بسپار',
  'auth.firstName': 'نام',
  'auth.lastName': 'نام خانوادگی',
  'quiz.title': 'سوال',
  'quiz.submit': 'ثبت',
  'quiz.quizFinish': 'پاسخ شما با موفقیت ثبت شد.',
  'quiz.answered': 'شما قبلا به این سوال پاسخ داده اید.',
  'home.title': 'اسامی برندگان مسابقه در جستجوی آرامش',
  'home.description': 'بیست و نهمین نمایشگاه بین المللی قرآن کریم',
  'error.notFound': '404 صفحه یافت نشد',
  'error.backHome': 'بازگشت به صفحه اصلی',
  'error.login': 'کدملی یا تلفن همراه نادرست می باشد',
  'error.register': 'ثبت نام نا معتبر می باشد',
};
